### ISSUE TITLE
在linux 3.13 中, 编译报错: mcount 未定义

### ISSUE THREAD

**Issue by yurenchen000** [Qunero/dnw4linux#1]
看到 天嵌 的, 直接就是一个应用程序, 不必牵扯内核.

这个应该 也可以做成 那样的吧

不过天嵌的 不是开源的: http://download.csdn.net/detail/guan506713512/6339089

**Comment by Qunero** [comment]
你上面提到的编译报错有没有具体日志？ mcount是啥意思？ 请贴一下日志；
另外你说的那个用qt写的界面应该挺好实现的。

**Comment by Qunero** [comment]
过期关闭。
